import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";

import Footer from "@/components/Footer";
import { Provider } from "react-redux";
import store from "@/redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js E-commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Getting Too many errors in latest version of Next.js  */}
        {/* <Provider store={store}> */}
        <Nav />
        <main className="pt-6 pb-10 md:min-h-[80vh]">
          <div className="container">{children}</div>
        </main>
        <Footer />
        {/* </Provider> */}
      </body>
    </html>
  );
}
